services:
  zelibot:
    build: .
    stdin_open: true
    environment:
      TOKEN: ${TOKEN}
      DB_PATH: /data/zelibot.db3   
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./data:/data
      - ./config:/config
